version: "3"
services:
  app:
    build: ./notification
    ports:
      - 8090:8090
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=amqp://rabbitmq
      - RABBIT_QUEUE=queueMail    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data: